# Generated by Django 3.2.16 on 2023-04-15 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('us_price', models.IntegerField()),
                ('bs_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.IntegerField(default=1)),
                ('us_total', models.IntegerField(null=True)),
                ('bs_cash', models.IntegerField()),
                ('bs_transfer', models.IntegerField()),
                ('date_sale', models.DateField(verbose_name=datetime.date.today)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirestcrud.product')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_income', models.DateTimeField(auto_now_add=True)),
                ('us_total', models.IntegerField()),
                ('bs_total', models.IntegerField()),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirestcrud.sale')),
            ],
        ),
    ]
