# Generated by Django 3.2.16 on 2023-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirestcrud', '0002_rename_amout_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='us_total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='us_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bs_cash',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bs_transfer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='us_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
