# Generated by Django 3.2.16 on 2023-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirestcrud', '0003_auto_20230415_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='us_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='us_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='us_total',
            field=models.FloatField(null=True),
        ),
    ]
