# Generated by Django 3.2.16 on 2023-04-15 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirestcrud', '0004_auto_20230415_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='day_income',
            field=models.DateTimeField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateField(auto_now_add=True),
        ),
    ]
