# Generated by Django 3.2.16 on 2023-04-15 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirestcrud', '0009_alter_income_day_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='day_income',
            field=models.DateTimeField(verbose_name=datetime.date.today),
        ),
    ]
